### ISSUE TITLE
Install latest does not work properly

### ISSUE THREAD

**Issue by AlexanderKrabbe** [StatisticsGreenland/pxmake#192]
Following these instruction from README.md: 

```
# install.packages('devtools')
# Latest release
devtools::install_github('StatisticsGreenland/pxmake/@*release')
```

Yield the following error:

```
> devtools::install_github('StatisticsGreenland/pxmake/@*release')
Error in parse_repo_spec(repo) : 
  Invalid git repo specification: 'StatisticsGreenland/pxmake/@*release'
```

I don't know if the error is in the tagging or in the way devtools install from github. 

Running

`devtools::install_github('StatisticsGreenland/pxmake@v0.9.1')`

install v0.9.1 fine.

**Comment by johan-ejstrud** [comment]
Hmm... It's looks like this approach has been [discontinued by GitHub](https://stackoverflow.com/a/40179557/16510400).

I can't find a new way to do this in one line, so I have just removed it from the documentation. People should be fine with installing the development version anyway, since we always keep the main branch stable. 😊
